theme: jekyll-theme-hacker
permalink: /blog/:year/:month/:day/:title
title: Matt Steward - Hands-On Full-Stack Development/Technical Lead 
description: Full-stack Technical/Team Lead: Experienced across multiple delivery models and business domains (including ~15 years in financial services/front-office), using a wide range of technologies and enterprise design patterns.
